### ISSUE TITLE
Not working - Godot 3.1.2

### ISSUE THREAD

**Issue by jakeonaut** [mnemoli/godotplacer#1]
Not sure if this is only versioned for a specific version up.

Here is the output I get in console after enabling the plugin and toggling Painting mode. clicking an area when having a scene selected in the FileSystem dock does not work.

```
Loading placer
 res://addons/placer/placer.gd:18 - Invalid call. Nonexistent function 'get_file_system_dock' in base 'EditorInterface'.
Painting toggled on
 res://addons/placer/placer.gd:112 - Invalid call. Nonexistent function 'get_selected' in base 'Nil'.
Painting toggled off
 res://addons/placer/placer.gd:48 - Invalid call. Nonexistent function 'free' in base 'Nil'.
Painting toggled on
 res://addons/placer/placer.gd:112 - Invalid call. Nonexistent function 'get_selected' in base 'Nil'.
Create Node
Painting toggled off
 res://addons/placer/placer.gd:48 - Invalid call. Nonexistent function 'free' in base 'Nil'
```

**Comment by Flavelius** [comment]
modify the script around line 18 to look like this:
```

for n in get_editor_interface().get_file_system_dock().get_children():
		if n is VSplitContainer:
			for c in n.get_children():
				if c is Tree:
					tree = c
					tree.connect("cell_selected", self, "file_picked")
					break
```

**Comment by jakeonaut** [comment]
That got me a similar error, but I think I found the issue. In 3.1 (I am using 3.1.2), there doesn't seem to be a FileSystemDock, at least not one you can get from the editor interface:

https://docs.godotengine.org/en/3.1/classes/class_editorinterface.html

Anyway, trying it in a 3.2+ version of Godot works perfectly as expected, and the scope of this plugin is probably not to support older versions, so I'll go ahead and close. Thank you for this really useful plugin!
